version: '3.1'
services:
  odoo16-web:
    image: odoo:16.0
    depends_on:
      - odoo16-db
    volumes:
      # - odoo-web-data:/var/lib/odoo
      - ./odoo.conf:/etc/odoo/odoo.conf
      # - ./odoo/addons:/mnt/extra-addons #to use this copy repo of odoo from git # git clone --branch 14.0 https://github.com/odoo/odoo.git
      - ./custom_apps:/mnt/custom_apps
    ports:
      - "8069:8069"
    environment:
      - HOST=odoo16-db
      - USER=odoo
      - PASSWORD=odoo
  odoo16-db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
